### ISSUE TITLE
Checkout breaks due to undefined variable

### ISSUE THREAD

**Issue by joshporter** [rulecom/rulemailer2#1]
Hello,

When an exception happens in the `CheckoutObserver` (I assume this was due to the module not being set up on my part) it does not catch the exception gracefully due to an undefined variable.

```
Message: Notice: Undefined property: Rule\RuleMailer\Observer\CheckoutObserver::$logger in /vendor/rulecom/rulemailer2/Observer/CheckoutObserver.php on line 54'
```

https://github.com/rulecom/rulemailer2/blob/master/Observer/CheckoutObserver.php#L54

Do you know when this can be fixed?

Thank you

**Comment by athe0i** [comment]
Thanks for your report. It should be fixed now. 

Regards
