### ISSUE TITLE
Get the email address earlier in the purchase process

### ISSUE THREAD

**Issue by swesam** [rulecom/rulemailer2#12]
If you register as a guest, fulfil the first step with your email and shipping addresses, go to the payment page and leave the website before finalising your purchase no basket abandonment is sent. 

As the user fill the email address field and go to the next page, it should be possible to use his email address and send him the email (following the exact same process as a registered customer). Is it something than could be done?

**Comment by robbanl** [comment]
I will add an feature toggle for this function, if we want it to be aggressive (log even though no login is made) so the shop owners self can decide if they want to have it or not. If I for example try my 10 different e-mail addresses and only logs in on the last one tried, I would get 9-10 abandoned cart e-mails (one for each mailbox) :)

**Comment by robbanl** [comment]
Ping @indiebytes
